version: "3.8"

services:
  proposal_monitor:
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    environment:
      - CONFIG_FILE=config/config.yml
    restart: unless-stopped

networks:
  backend:
    driver: bridge
