# Global settings
proposal_detail_domain: "https://www.mintscan.io" # The base URL for viewing proposal details. This can be customized if you use a different domain.
voting_alert_behavior_nearing: "only_if_not_voted" # Specifies when to send alerts near the end of the voting period. Options: "always" to always send alerts, "only_if_not_voted" to send alerts only if the validator hasn't voted.

#Discord Settings
discord:
  enabled: no
  webhook: "https://discord.com/api/webhooks/path" # The Discord webhook URL to send alerts.

# Chains to be monitored
chains:
  "Axelar":
    chain_id: "axelar-dojo-1" # The ID of the chain.
    validator_address: "your_validator_address_here" # The address of the validator to monitor.
    sdk_version: "v1" # The version of the Cosmos SDK API to use. Options are "v1" or "v1beta1".
    api_endpoint: "https://yourdomain.com" # The API endpoint to fetch proposals.
    explorer_url: "https://www.mintscan.io/axelar/proposals"
    alerts:
      discord:
        enabled: yes
        webhook: "" # uses default if blank
