name: SonarCloud
on:
  push:
    branches:
      - main
      - develop
      - sonarcloud
      - refactor
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: read

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          fetch-depth: 0
      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
